#+TITLE: Dashboard for Survival Curve Extraction Based on Guyot et al. 2012 
#+AUTHOR: Chong Hoon Kim
#+EMAIL: chong.kim@ucdenver.edu
#+DATE: 1/12/2018
#+HTML_HEAD: <style>#content {width: 850px; margin-left: 50px; margin-bottom: 40px; padding: 20px; background: #fff;}
#+HTML_HEAD: body {background: #eee;}
#+HTML_HEAD: #postamble {margin-left: 50px; background: #eee;}</style>style>
#+PROPERTY: header-args:R :session *R* :tangle yes :comments no :eval no-export

# TODO About this document.
# - disclaimer: Many questions will remain open but at least this tutorial will put you in the position to ask those questions.
# - feel free to use issue tracker and PRs are welcome
# - reference to tangled code



* README

This repository contains the codes necessary to produce an interactive shiny dash board that can be found at https://pharmacoecon.shinyapps.io/SurvivalCurveExtraction/. The original [[https://bmcmedresmethodol.biomedcentral.com/articles/10.1186/1471-2288-12-9][Guyot et al]]'s code is embedded in the dashboard. The original purpose of the document was to serve as the analysis toolkit for generating survival distribution parameters and fit statistics for health technology assessment (HTA) or cost-effectiveness analysis of pharmaceutical interventions. The dashboard entails:

0. Before embarking on the use of the dashboard, please have the necessary data files extracted from previous studies as illsutrated in [[https://github.com/ck2136/SurvivalCurveExtraction/blob/master/SurvivalExtractionforCEA.ipynb][Jupyter Notbook Tutorial]].
1. Allowing user to input datasets (as csv) and provide summary statistics of simulated Individual Patient Data (IPD) generated from survival plots of other studies.
2. Users can specify which distributions to include (e.g. Weibull, Gompertz, and even Splines).
3. Graphical display of the Kaplan-Meier plot and fitted parametric and semi-parametric distributions can also be extracted through the dashboard.
4. Parameters of the parametric distributions and fit statistics can be obtained..
